// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/domain/postpayment.go
//
// Generated by this command:
//
//	mockgen -source=/Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/domain/postpayment.go -destination=/Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/domain/mocks/mock_postpayment.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPostPaymentService is a mock of PostPaymentService interface.
type MockPostPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPostPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPostPaymentServiceMockRecorder is the mock recorder for MockPostPaymentService.
type MockPostPaymentServiceMockRecorder struct {
	mock *MockPostPaymentService
}

// NewMockPostPaymentService creates a new mock instance.
func NewMockPostPaymentService(ctrl *gomock.Controller) *MockPostPaymentService {
	mock := &MockPostPaymentService{ctrl: ctrl}
	mock.recorder = &MockPostPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostPaymentService) EXPECT() *MockPostPaymentServiceMockRecorder {
	return m.recorder
}

// PostPayment mocks base method.
func (m *MockPostPaymentService) PostPayment(request *models.PostPaymentRequest) (*models.PostPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPayment", request)
	ret0, _ := ret[0].(*models.PostPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostPayment indicates an expected call of PostPayment.
func (mr *MockPostPaymentServiceMockRecorder) PostPayment(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPayment", reflect.TypeOf((*MockPostPaymentService)(nil).PostPayment), request)
}
