// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/client/client.go
//
// Generated by this command:
//
//	mockgen -source=/Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/client/client.go -destination=/Users/ehsanashouri/go/src/github.com/redscaresu/payment-gateway-challenge-go-1/internal/client/mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// PostBankPayment mocks base method.
func (m *MockClient) PostBankPayment(request *models.PostPaymentBankRequest) (*models.PostPaymentBankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBankPayment", request)
	ret0, _ := ret[0].(*models.PostPaymentBankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostBankPayment indicates an expected call of PostBankPayment.
func (mr *MockClientMockRecorder) PostBankPayment(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBankPayment", reflect.TypeOf((*MockClient)(nil).PostBankPayment), request)
}
